Fix connector instantiation exceptions in Tests
Many tests would throw the following exception when
instantiating test connectors:

WARNING: Unable to read application context properties.
PropertiesException: Unable to read application context properties file:
Spring exception while getting ApplicationContextProperties bean:
No bean named 'ApplicationContextProperties' is defined
	at Context.loadConnectorManagerProperties(Context.java:902)
	at Context.getConnectorManagerProperties(Context.java:876)
	at Context.getProperty(Context.java:1147)
	at Context.getGsaFeedHost(Context.java:1114)
	at ConnectorCoordinatorImpl.addGoogleProperties(ConnectorCoordinatorImpl.java:1150)
	at ConnectorCoordinatorImpl.resetConfig(ConnectorCoordinatorImpl.java:1011)
	at ConnectorCoordinatorImpl.createNewConnector(ConnectorCoordinatorImpl.java:972)
	at ConnectorCoordinatorImpl.setConnectorConfiguration(ConnectorCoordinatorImpl.java:650)

These started appearing with revision r2883, which adds the
GSA host address to the google* properties for the connector.
In general the tests wouldn't fail, but the output logs were
full of these exceptions.

This change adds a ApplicationContextProperties bean to the
TestContext.xml used directly or indirectly by many tests.

Change Log:
----------
M projects/connector-manager/testdata/contextTests/TestContext.xml